theme: jekyll-theme-minimal
logo: https://media.licdn.com/dms/image/D5603AQEU9h6vlTP09Q/profile-displayphoto-shrink_400_400/0/1686732067642?e=1723075200&v=beta&t=uBbWWKm7gN-fuxYLtnFgOjx6C6r3E3alLBRUzPgZeDk
title: Bioinformatics Fun with Yi Hung Leeeeee
